import {
  heroImage,
  profilePic,
  adesso,
  allhers,
  avecamxur,
  ccc,
  guider,
  hhu,
  kirrvn,
  ngs,
  tdt,
  aftereffects,
  angular,
  aws,
  azure,
  bard,
  blazor,
  blender,
  contentful,
  csharp,
  css,
  docker,
  figma,
  firebase,
  git,
  googleads,
  googlebusiness,
  html,
  illustrator,
  java,
  javascript,
  springboot,
  mailchimp,
  make,
  meta,
  mongodb,
  mysql,
  nextjs,
  openai,
  photoshop,
  php,
  premierepro,
  python,
  pytorch,
  react,
  sanity,
  shopify,
  shopifyliquid,
  strapi,
  tailwindcss,
  threejs,
  tiktok,
  typescript,
  unity,
  unreal,
  vuejs,
  chatgpt,
  imagegen,
  pokedex,
} from "../public/index.js";

export const socials = [
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/fabianfarid/",
  },
  {
    name: "GitHub",
    url: "https://github.com/farazfarid",
  },
  {
    name: "E-Mail",
    url: "#contact",
  },
];

export const about = [
  {
    name: "Fabian Faraz Farid",
    role: "Software Engineer",
    heroImage: heroImage,
    about:
      "I'm a versatile software developer with a passion for crafting exceptional web experiences. Beyond front-end finesse and back-end mastery (TypeScript, Angular, React), I bring expertise in AI tools and game development (Unity, C#). My keen eye for business extends beyond code, empowering small businesses through marketing consultations and platform optimization (Shopify, Meta, Google Ads).\n Fueled by a love for innovation, I led the creation of the local-multiplayer game 'Two Men Dungeon' as CEO and Founder of Nova Game Studios. As Chief Information Officer for Avec Amxur, Kirrvn, The Driving School, and as Chief Technology Officer for All Hers Official, I spearhead website design, ad campaigns, and logistics optimization while refining content delivery skills (Contentful, Strapi) and email automation (Mailchimp, Make).\nI'm an avid learner, collaborator, and problem-solver, always looking for the next coding adventure. When I'm not crafting digital solutions, you'll find me perfecting three-pointers on the basketball court or exploring new horizons as a passionate traveler.\n\nLet's code something extraordinary together!",
    profilePic: profilePic,
    location: "Germany",
  },
];

export const skills = [
  {
    name: aftereffects,
    level: 35,
    image: aftereffects,
  },
  {
    name: angular,
    level: 75,
    image: angular,
  },
  {
    name: aws,
    level: 35,
    image: aws,
  },
  {
    name: azure,
    level: 35,
    image: azure,
  },
  {
    name: bard,
    level: 100,
    image: bard,
  },
  {
    name: blazor,
    level: 35,
    image: blazor,
  },
  {
    name: blender,
    level: 35,
    image: blender,
  },
  {
    name: contentful,
    level: 80,
    image: contentful,
  },
  {
    name: csharp,
    level: 75,
    image: csharp,
  },
  { name: css, level: 80, image: css },
  { name: docker, level: 35, image: docker },
  { name: figma, level: 90, image: figma },
  { name: firebase, level: 35, image: firebase },
  { name: git, level: 100, image: git },
  { name: googleads, level: 75, image: googleads },
  { name: googlebusiness, level: 100, image: googlebusiness },
  { name: html, level: 100, image: html },
  { name: illustrator, level: 35, image: illustrator },
  { name: java, level: 80, image: java },
  { name: javascript, level: 80, image: javascript },
  { name: springboot, level: 65, image: springboot },
  { name: mailchimp, level: 100, image: mailchimp },
  { name: make, level: 100, image: make },
  { name: meta, level: 80, image: meta },
  { name: mongodb, level: 75, image: mongodb },
  { name: mysql, level: 75, image: mysql },
  {
    name: nextjs,
    level: 80,
    image: nextjs,
  },
  { name: openai, level: 100, image: openai },
  { name: photoshop, level: 65, image: photoshop },
  { name: php, level: 45, image: php },
  { name: premierepro, level: 45, image: premierepro },
  { name: python, level: 60, image: python },
  { name: pytorch, level: 40, image: pytorch },
  { name: react, level: 80, image: react },
  { name: sanity, level: 100, image: sanity },
  { name: shopify, level: 100, image: shopify },
  { name: shopifyliquid, level: 100, image: shopifyliquid },
  { name: strapi, level: 90, image: strapi },
  { name: tailwindcss, level: 100, image: tailwindcss },
  { name: threejs, level: 100, image: threejs },
  { name: tiktok, level: 50, image: tiktok },
  { name: typescript, level: 80, image: typescript },
  { name: unity, level: 100, image: unity },
  { name: unreal, level: 45, image: unreal },
  { name: vuejs, level: 35, image: vuejs },
];

export const experiences = [
  {
    id: 1,
    title: "CEO & Founder",
    company_image: ngs,
    company_name: "Nova Game Studios",
    date: "May 2015 - May 2019",
    skills: [unity, csharp, blender, html, css, php, javascript, mysql],
    points: [
      "Developing a Local-Multiplayer Game 'Two Men Dungeon'",
      "Character design and Animation of characters with Blender",
      "Implementation of the game with the Engine Unity in C#",
      "Programming a website for the public in HTML, CSS, PHP und JavaScript, Administration of user data in MySQL",
    ],
  },
  {
    id: 2,
    title: "Lead Software Engineer",
    company_image: ccc,
    company_name: "Comet Cine Center",
    date: "April 2020 - July 2020",
    skills: [java, springboot, mysql, html, css],
    points: [
      "Cinema administration and booking system in Java Spring Boot",
      "Design of a technological architecture with class diagrams based on Domain Driven Design",
      "Specification of a data set for the Cinema administration and the connection of movies to the cinema hall with an UML-Diagram",
      "Programming of a User Interface with Login-Screen in Thymeleaf, Administration of user data in a MySQL-Database",
    ],
  },
  {
    id: 3,
    title: "Lead Software Engineer",
    company_image: hhu,
    company_name: "Heinrich-Heine-University",
    date: "July 2020 - October 2020",
    skills: [java, springboot, mongodb, html, css],
    points: [
      "Usage of the Springboot Framework to create the Web-Application for control and surveillance of the customer number in a store",
      "Implementation of a Backend for the customer class with the attributes: healthy, recovered, vaccinated. Development of special rights for emergency services",
      "Communication of data is done through the given internal network by sending the number of customers to each entrance control",
      "JUnit Tests for validating the methods",
    ],
  },
  {
    id: 4,
    title: "Software Engineer",
    company_image: adesso,
    company_name: "adesso SE",
    date: "October 2021 - Present",
    skills: [
      html,
      css,
      javascript,
      typescript,
      angular,
      java,
      springboot,
      mongodb,
    ],
    points: [
      "Programming Websites and Web Apps using Angular with HTML, CSS and Typescript",
      "MEAN Full Stack Development with Java Springboot",
      "Agile Software Development with Scrum and Kanban",
      "Working on part of the company's ERP system with programming a time tracking system in Angular and Typescript",
      "Working on digital parking solutions for the company to optimise the process of handling park tickets for the company's underground car parking",
    ],
  },
  {
    id: 5,
    title: "Chief Information Officer",
    company_image: avecamxur,
    company_name: "Avec Amxur",
    date: "November 2021 - July 2023",
    skills: [
      shopify,
      shopifyliquid,
      html,
      css,
      javascript,
      photoshop,
      illustrator,
      googleads,
      googlebusiness,
      meta,
      tiktok,
    ],
    points: [
      "Spearheaded the implementation of Shopify as the company's e-commerce platform, aligning scalability and security needs with growth goals",
      "Implemented creative solutions like utilizing Adobe Photoshop and Illustrator for internal design needs, keeping operational costs lean while maintaining professional visuals",
      "Collaborated directly with the CEO to implement data-driven marketing strategies through tools like Google Ads and Meta Business Suite, optimizing investment and measuring ROI",
    ],
  },
  {
    id: 6,
    title: "Chief Information Officer",
    company_image: kirrvn,
    company_name: "Kirrvn",
    date: "December 2021 - October 2023",
    skills: [
      shopify,
      shopifyliquid,
      html,
      css,
      javascript,
      photoshop,
      illustrator,
    ],
    points: [
      "Spearheaded the implementation of Shopify as the company's e-commerce platform, aligning scalability and security needs with growth goals",
      "Developed a digital asset management system to ensure brand consistency across all digital touchpoints, from website graphics to social media",
      "Managed the IT budget responsibly, prioritizing resources to maximize impact on customer acquisition and brand awareness",
      "Provided IT support and training directly to the CEO, bridging technical gaps and ensuring continuity of operations",
      "Implemented creative solutions like utilizing Adobe Photoshop and Illustrator for internal design needs, keeping operational costs lean while maintaining professional visuals",
    ],
  },
  {
    id: 7,
    title: "Software Engineer",
    company_image: guider,
    company_name: "Guider",
    date: "September 2022 - Present",
    skills: [
      html,
      css,
      javascript,
      typescript,
      react,
      contentful,
      strapi,
      mailchimp,
      make,
    ],
    points: [
      "Pushing content using Contentful and Strapi",
      "Creating e-mail automations for growth and customer experience using Make (formerly Integromat) and Mailchimp",
      "Writing Audio versions of the company's content utilising Google Workspace",
    ],
  },
  {
    id: 8,
    title: "Chief Information Officer",
    company_image: tdt,
    company_name: "The Driving Teacher",
    date: "October 2022 - Present",
    skills: [
      html,
      css,
      javascript,
      photoshop,
      illustrator,
      premierepro,
      aftereffects,
      googlebusiness,
      googleads,
    ],
    points: [
      "Collaborated directly with the CEO to define the company's digital presence strategy, aligning technology choices with marketing and business objectives",
      "Leveraged Adobe Creative Suite (Photoshop, Illustrator, After Effects, Premiere Pro) to create high-quality visual assets, including website graphics and an engaging intro animation for the YouTube channel",
      "Established a Google Business profile, optimizing local SEO and online visibility to attract and convert new students",
    ],
  },
  {
    id: 9,
    title: "Chief Technology Officer",
    company_image: allhers,
    company_name: "All Hers Official",
    date: "December 2022 - December 2023",
    skills: [
      shopify,
      shopifyliquid,
      html,
      css,
      javascript,
      photoshop,
      illustrator,
      premierepro,
    ],
    points: [
      "Spearheaded the implementation of Shopify as the company's e-commerce platform, aligning scalability and security needs with growth goals",
      "Leveraged Adobe Creative Suite (Photoshop, Illustrator, Premiere Pro) to create high-quality visual assets, including website graphics and an engaging reel for social media (Instagram, TikTok)",
      "Proactively researched and proposed emerging technologies relevant to the logistics industry in Egypt, staying ahead of the curve and maximizing future competitive advantage",
    ],
  },
];

export const projects = [
  {
    name: "ChatGPT Clone",
    image: chatgpt,
    url: "https://chatgpt.farazfarid.me/",
    description:
      "Craving a next-level chatbot experience? Buckle up for ChatGPT Messenger 2.0, crafted with the future in mind. Using Next.js 13's cutting-edge framework, I'm taking chatbots beyond basic scripts. Dive deep into AI magic, craft personalized conversations using OpenAI's API with Firebase's real-time power, and enjoy a sleek, responsive interface brought to life by Tailwind CSS. Get ready to redefine how you connect!",
    skills: [react, tailwindcss, openai, firebase],
  },
  {
    name: "AI Image Generator",
    image: imagegen,
    url: "https://image-generator.farazfarid.me/",
    description:
      "Unlock the surreal landscapes of your imagination with my DALL·E 3 Image Generator, where art and code collide in breathtaking harmony. Built on Next.js 13's cutting-edge framework, I've harnessed the creative power of OpenAI's API to bring your wildest visions to life. Dream up personalized prompts, watch Azure Functions weave their magic, and marvel as secure image handling safeguards your masterpieces. Explore an elevated UI, crafted with TypeScript's precision, for a truly immersive experience. Ready to paint the world with AI? Let's create together!",
    skills: [react, tailwindcss, openai, azure],
  },
  {
    name: "PokéDex",
    image: pokedex,
    url: "https://pokedex.farazfarid.me/",
    description:
      "Calling all Pokémon trainers! Embark on a quest for React.js mastery with my meticulously crafted Pokédex. Journey through challenges like fetching data with fetch API, rendering stunning tables with calculated power, and navigating with intuitive pagination. Master search skills to uncover hidden Pokémon potential and filter by power thresholds. Embrace the beauty of TailwindCSS for a UI that's as captivating as a Charizard's flame. Witness a project structure built on SOLID principles, crafted for maintainability and performance that's faster than a Pikachu's Quick Attack. Ready to prove your React.js expertise? Let's catch 'em all!",
    skills: [react, tailwindcss],
  },
];
